### ISSUE TITLE
Serverlabel erlaubt keine '-'

### ISSUE THREAD

**Issue by crosscodr** [virtUOS/studip-meeting#263]
Ich habe versucht für einen Server ein Serverlabel mit '-' anzugeben und zu speichern. Daraufhin kam folgende (falsche) Fehlermeldung:

> Der Treiber BigBlueButton kann nicht verwendet werden, da er keinen Server hat.
Es wäre gut, nicht erlaubte Zeichen direkt bei der Eingabe abzufangen. Aber ich frage mich, warum ein '-' nicht gehen soll.
Unabhängig davon ist die Fehlermeldung die beim speichern angezeigt wird falsch.

**Comment by ferishili** [comment]
@crosscodr,
As I tested this issue several times, there is no such problem. The checker for server config only uses the url and api-salt and has nothing to do with label. Based on that, I assume that the problem is about invalid url or api-salt. Please try it out with valid url and api-key and let me know (in case the problem resists) the exact label text.
The labels I tried were: 'Server-1', 'copied from test-server', 'there-is-no-problem' :D

**Comment by ferishili** [comment]
![Screenshot from 2021-05-05 12-57-50](https://user-images.githubusercontent.com/53179227/117131283-87865600-ada1-11eb-8804-1e1627de2bb9.png)

**Comment by crosscodr** [comment]
Hi @ferishili,
sorry, it must have been a local caching problem. I cleared my browser cache and now the error is gone. Nevermind.
