### ISSUE TITLE
Breakouträume

### ISSUE THREAD

**Issue by tgloeggl** [virtUOS/studip-meeting#82]
BBB bietet Breakouträume - wie funktioniert das, was genau tun die, brauchen wir da was für im Plugin?

**Comment by ferishili** [comment]
Breakout rooms are smaller subsets of main rooms which help moderator to divide and group up the participants in rooms with desired duration. It is possible for Moderators to create at least 2 Breakout rooms and set the duration in minutes and assign participants by drag and drop.

Based on BBB API functionalities, it is possible to implement Breakout rooms:
- In addition to general features (default parameters), there should be 4 more parameters specifically to create breakout rooms; isBreakout, parentMeetingID, sequence and freeJoin are required to handle Breakout rooms.

In my opinion and since BBB itself provide a sufficient Breakout room management, I don't think that can be feasible to have it in the Plugin:
The first challenge is that we need to come up with a system that can handle division of the participants into breakout rooms created in Plugin!

**Comment by tgloeggl** [comment]
I completely agree
